[features]
seeds = false
skip-lint = false
[programs.devnet]
labofi_solana_smart_contract = "Gu2gc5Xz4RSDGr3bv8PKZa48cNyYiCaRkT49jZz91DD2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
