[features]
seeds = false
skip-lint = false
[programs.localnet]
labofi_solana_smart_contract = "AYuNbYZ6tbHz6hqRKxFmfc7pGZARj4XAFvuiAaBgmK6W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
