[features]
seeds = true
skip-lint = false
[programs.devnet]
labofi_solana_smart_contract = "ANYpUxvMWd5pBwGDf4cTejCYCJTP5ecrSof968gcFGBT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
