[features]
seeds = false
skip-lint = false
[programs.devnet]
labofi_solana_smart_contract = "DokRp5Lx8SPTfVLXzYC1LiLdJE8YSGSX4e9mPfuDD9Mu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
